#!/bin/bash
total_chapters=10
if [ -f .current_level ]
then
  current_level=$(<.current_level)
else
  current_level=1
fi

next_level=$[(current_level%total_chapters)+1]
echo $next_level > .current_level
echo "Moving to savepoint:" $next_level

rm -r ./backend/ ./frontend/
mkdir -p ./backend/ ./frontend/

exclude_files_backend=(save-points/$next_level/backend/node_modules
                       save-points/$next_level/backend/package.json
                       save-points/$next_level/backend/package-lock.json
                       save-points/$next_level/backend/woofer.sqlite)

rsync -av -q --exclude="${exclude_files_backend[@]}" save-points/$next_level/backend/ backend/

exclude_files_frontend=(save-points/$next_level/backend/node_modules
                       save-points/$next_level/backend/package.json
                       save-points/$next_level/backend/package-lock.json)

rsync -av -q --exclude="${exclude_files_frontend[@]}" save-points/$next_level/frontend/ frontend/