#!/usr/bin/env bash

level=${1:-1}
echo $level > .current_level
echo "Resetting to save point:" $level

rsync -av -q save-points/$level/backend/ backend/

rsync -av -q save-points/$level/frontend/ frontend/