name: Push-to-EC2

on: push

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----MIIEowIBAAKCAQEAjyG3Ej6UAyXgy4LP9R7VTydoobb9eeW8y8rLS4VQJmdnVUbOf7ywrqG1D7VGxsgu+E6bFImXN4A3WZ/+JPPiUNoxEqWALWDsWzYByPINmWFIyJ96JQpuDB11j0zWeZUN2T3uXVeR9bdiC+C5wo8bsWPptisUKVtSYiiOQ/8G52ZnUnO128X7qTxOZ60VufISAcgVgWimu4A4vL4vImytFw8Li5VbpGz3TfVuK1opPfvVWbMqwmKMHfkJLa5+TG6WxAyuWzWApTp57ZKiyGJ0zhpEKB9Vvk6SmX76pHrqtWmHweKFa9Wz1YMfwGRO+0jOAXIQ0T2hEeJwEJVpb18bjwIDAQABAoIBAER/CwBVKDoVb22VDXYtqkE2B9GUI9upAN+6De33P3MRexcJSptAroDz7BU3WEaa2DeGTprWeaJa3qIqedIvUHgG4wMcZqnQv2uq/dGvXKixMMap4ydExYNQuci5Kc6HcVgsVh0fYj9n4ijzA5LDL6qFuPuvw/dCt7s301Vg/2nPE/RdmjpyX+N3Wc7Hw+ZjB99QPtVEPiql8dk04Bc/A1b5qfIRvW6ty3ykGL1Nko4/wmxWFfUfiItFOMCNB6RR6mKjToKxFTneSP/6z6ZSkq3eQXdRpdM7nab4PqZcM1v2MoP9cC4Atd0eokSbVg9DYLilodX/2XSuwemfdlBTh8ECgYEA2wa1tg74d4Uch/vVpIre0AbXu8fP1p/OUPctYLVPPMZ/5F6dvRnT+0g69SfeatP3wECK+glf3n/CZNffSdGJ9RsH9bp7DEj+aYQhtQsy77fEIJ9183rUCDVNLZw/I6aLn0F/38P9aSIlk7sNMIFWbnfzQlDMjIrzAK4bBvaB5+8CgYEAp0sy7AWb2D+ne3jlmTYi5zG7kABXLtndFLJi1TM5zoazb5hrt+gv0VIkDSSjB+9hVVP871bo4zCkZP8E/Gzn/RmbKal1FQ42oxsbeHFpVbE4W/0yTu+QknN9609e61r2DId4g1QsEpfWY64NzmwGsqnjrLhfpknURg4O/+ETZmECgYEAlU7pqIZkEvYHERw388dHRQClKDl6EZE3EDKwGHEA5ylaHc/yL+rfezkuF9lp4eFFzyUwmGqzk/X8CsquSKAzL4eR0Y2iPCm2ZS/R2p0byBa5+JM70RM2X7IWPrV4xVDPdW0tQtlUcsr4WtD0mNBSn1Pd3KNADb7bEOefPQvmWrkCgYB6+2sZ2x2wIUtMF5ohwYxzDTpnJ/jvdjVyK5lARgIu8xMh7Jjzf3r3lDzwdIhtIusYwT9l6ywVKAMSQ+80ahM5GwPX4r0xl1tPGHRfXHAlELzv0viS0sYjA0gEHjsXJa1PlJ9hXBVyLbDrYl6/6uYZnY7DwF6AbjHgtiEMtjd+wQKBgH6UUaMcVtuKvyeqUFuMKBuS5qYLelb6ApyNFSQ3qAnWgWZZnVtncfO9CwBNqy+R+MdKTM7nRINTQaesPpuscFgbJyWnVgN0IUqEltL6OESjvbudvB5WPTyBwaPdLXoOyhFuaTuPIMebzrZkTu7G4fZ/RIsaASqrv6mD4Ncw5AGo-----END RSA PRIVATE KEY-----"
          SOURCE: "backend"
          REMOTE_HOST: "ec2-13-233-137-73.ap-south-1.compute.amazonaws.com"
          REMOTE_USER: "ec2-user"
          TARGET: "/home/ec2-user/web-dev-workshop"
          EXCLUDE: "/node_modules/"
